<<<<<<< HEAD
title: Modernist theme
description: Modernist is a theme for GitHub Pages.
show_downloads: true
google_analytics:
=======
>>>>>>> 58b9666c3714daa6f4bbe4c257d62d896e7b228e
theme: jekyll-theme-modernist